name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and test the Docker image
      run: docker build .
    - name: "Set vars"
      run: echo "TIMESTAMP_TAG=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image to repositories
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          arkaitzj/knife:${{ env.TIMESTAMP_TAG }}
          ghcr.io/arkaitz/knife:${{ env.TIMESTAMP_TAG }}
        cache-from: |
          type=registry,ref=arkaitzj/knife:main-latest
          type=registry,ref=arkaitzj/knife:${{ github.ref_name }}-latest
        cache-to: |
          type=registry,ref=arkaitzj/knife:${{ github.ref_name }}-latest,mode=max

      
      
