name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TIMESTAMP_TAG: $(date +%s)
    steps:
    - uses: actions/checkout@v3
    - name: Build and test the Docker image
      run: docker build .
    - name: "Set vars"
      run: echo "TIMESTAMP_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: Show the timestamp tag
      run: echo $TIMESTAMP_TAG
    - name: Push image to repositories
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          arkaitzj/knife:${{ env.TIMESTAMP_TAG }}
          ghcr.io/arkaitz/knife:${{ env.TIMESTAMP_TAG }}
      
      
